[package]
name = "advent04"
version = "0.1.0"
authors = ["Sascha Meiers <sascha.meiers.embl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
